# Generated by Django 4.1.7 on 2023-03-12 19:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loacation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
