# Generated by Django 4.1.7 on 2023-03-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_loacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='loacation',
            new_name='location',
        ),
    ]
